### ISSUE TITLE
Issue on call back

### ISSUE THREAD

**Issue by cun** [KellyLSB/PHP-PayPal-API-Class#1]
Hi KellyLSB

I've just tried to use you Class,which is some cool method of doing PayPal payments by the way!

however, Im continually getting the error 

"Notice: Undefined index: PP_TOKEN in paypal.class.php on line 239"

The line in question is $PP_TOKEN = $_COOKIE['PP_TOKEN'];

It's not able to find the COOKIE, now I've done a little digging and I believe its something to do with how CURL intercepts SSL maybe? I'm not sure but it'scompletely rendering this class unusable.

Owww also, you have a spelling  mistake on a VAR, See the line 
$this->add_nvp('L_PAYMENTREQUEST_0_NAME'.$key, $item['NAME']);

In the example at the top you had in the array "NME" and it stopped the code too from working, but I managed to figure that one out ;)

If you could help me at all KellyLSD, I'd really appeciate it!

Cheers
Dan.

**Comment by KellyLSB** [comment]
Hi Dan,

Yes that error on like 239 was because the line above it was not returning properly. I changed the method to use empty instead of not which will cause it to return if the cookie is not set, evaluates to false, or an empty string.

As for the typo you caught in my example text. Thank you and it has been updated.

Thanks,
Kelly

**Comment by cun** [comment]
Brilliant thank you!

I've just updated my code, It seems to go through now, However I can't seem to figure something else out. I'll see if It's just me being stupid coding at 2am syndrome!

Once again thanks for the speedy reply! 
Dan.

**Comment by KellyLSB** [comment]
What is the issue? I might be able to help out.

**Comment by cun** [comment]
OK, I hope I can explain this, 

I've got the return page from page after the paypal payment, It has pushed me to my RETURN url, 
However, the following code isn't doing what it's supposed to do.

$paypal->express_checkout(
    array(
       'IPN_URL' => 'http://my.ipn/handler.php'
    ), 'process'
 );

(Obviously i have the IPN_URL set to the IPN file on my server and inside that is a call to the $this->process_ipn(); function, however I'm stuck with a blank screen. Would this have anything to do with Paypal not being able to see my IPN url at all? As I'm working on an internal development box...

**Comment by KellyLSB** [comment]
Ok the IPN Url is for the Instant Payment Notifications (It establishes a Webhook) You never actually will go to that page as an end user. The process_ipn() method returns an array of data filled with transaction information. The IPN Url in called on payment complete etc... This is most helpful for when you want to update your database when the money has been fully processed and landed in your merchant account.

IPN Information https://www.paypal.com/ipn/

And yes the IPN Url must be visible to the internet.

If you need a good web environment to test with I would recomend using Heroku Cedar Stack with the Build pack on my Github account.

**Comment by cun** [comment]
Cheers once again Kelly! Most informative! I'll give this a whirl! 

Kindest Regards
Dan.

**Comment by KellyLSB** [comment]
Anytime. Hit me up via email if you need anything else kbecker@kellybecker.me.

**Comment by cun** [comment]
Brilliant will keep that in mind, Thank you.
I've just followed you on twitter about an hour ago too so I don't loose contact. ;)
